### ISSUE TITLE
error last update

### ISSUE THREAD

**Issue by evanillaa** [qbcore-framework/qb-input#8]
![5555](https://user-images.githubusercontent.com/80897991/146768246-6fcba862-8cd2-4c7c-8f23-bb2ba6dc5f04.png)

**Comment by evanillaa** [comment]
https://github.com/qbcore-framework/qb-input/pull/7
@WaydeTheKiwi

**Comment by idrp** [comment]
![image](https://user-images.githubusercontent.com/88186466/147266516-81dacf97-cbaf-4493-bb12-99e3b0d43b64.png)
also getting this error

**Comment by WaydeTheKiwi** [comment]
I'll away with little access to computer. I'll look when I can. If no one
else needs the css ids I added just revert before this was added

**Comment by WaydeTheKiwi** [comment]
Fixed with commit #9 - let me know if it works

**Comment by jhnoi146** [comment]
i redownload and have same problem, qb-imput/html/scripts.js.178

**Comment by Duguayster** [comment]
Fresh install of QBCore, also getting this same error.

Issue here when trying to open a police evidence stash....
![qb-input-error-178](https://user-images.githubusercontent.com/31002773/147406541-8ac6ea38-350f-4a32-b5de-29649dc8b4f4.png)

**Comment by jhnoi146** [comment]
plz resolve this

**Comment by WaydeTheKiwi** [comment]
Did you pull from #9 ? or from main branch, as it hasnt been pushed yet

**Comment by jhnoi146** [comment]
fixed
